package(
    default_applicable_licenses = ["//:license"],
    default_hdrs_check = "strict",
    default_visibility = [
        "//:__subpackages__",
    ],
)

filegroup(
    name = "testdata",
    srcs = glob(["*"]),
)
