package(
    default_applicable_licenses = ["//third_party/odml:license"],
    default_hdrs_check = "strict",
    default_visibility = [
        "//visibility:public",
    ],
)

filegroup(
    name = "testdata",
    srcs = glob(["*"]),
)
