name: "CI"
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  presubmit:
    name: "Presubmit"
    runs-on: Linux_runner_8_core
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore bazel cache
        uses: actions/cache/restore@v4
        id: bazel-cache
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazel-linux
            ~/.cache/bazel-android
          key: ${{ github.workflow }}-${{ hashFiles('**/WORKSPACE') }}-${{ hashFiles('**/BUILD*') }}
          restore-keys: |
            ${{ github.workflow }}-${{ hashFiles('**/WORKSPACE') }}-
            ${{ github.workflow }}-

      - name: Check cache hit
        run: |
          echo "Cache Hit: ${{ steps.bazel-cache.outputs.cache-hit }}"
          echo "Cache Primary Key: ${{ steps.bazel-cache.outputs.cache-primary-key }}"
          echo "Cache Matched Key: ${{ steps.bazel-cache.outputs.cache-matched-key }}"

      - name: Run bazel build on Linux
        run: |
          bazel build --disk_cache=~/.cache/bazel-linux \
          //runtime/engine:litert_lm_main

      - name: Run bazel test on Linux
        run: |
          bazel test --disk_cache=~/.cache/bazel-linux \
            //runtime/components:all \
            //runtime/core:all \
            //runtime/engine:all \
            //runtime/executor:all \
            //runtime/util:all

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28b
          add-to-path: false

      - name: Run bazel build on Android
        run: |
          bazel build --disk_cache=~/.cache/bazel-android \
            --config=android_arm64 \
            //runtime/engine:litert_lm_main
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Save bazel cache if new or changed on push.
        uses: actions/cache/save@v4
        if: ${{ steps.bazel-cache.outputs.cache-hit }} != 'true' || ${{ github.event_name }} == 'push'
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazel-linux
            ~/.cache/bazel-android
          key: ${{ github.workflow }}-${{ hashFiles('**/WORKSPACE') }}-${{ hashFiles('**/BUILD*') }}

